# Generated by Django 3.2.9 on 2022-01-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travel_time',
        ),
        migrations.AddField(
            model_name='route',
            name='travel_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='travel_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
