# Generated by Django 3.2.9 on 2022-01-28 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_transport', models.CharField(choices=[('R', 'Running'), ('B', 'Biking')], default='R', max_length=1)),
                ('travel_distance', models.IntegerField()),
                ('travel_time', models.TimeField()),
                ('date_created', models.DateField(verbose_name='Date traveled')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.route')),
            ],
        ),
    ]
