# Generated by Django 3.2.9 on 2022-01-31 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220131_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Describe your route in detail:'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of route:'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miles:'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
