# Generated by Django 3.2.9 on 2022-02-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220201_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='fav_route',
        ),
    ]
