# Generated by Django 3.2.9 on 2022-02-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_favorite_fav_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='mode_of_transport',
            field=models.CharField(choices=[('Run', 'Run'), ('Bike', 'Bike')], default='Run', max_length=20),
        ),
    ]
